# Introduction to `numpy` and `matplotlib`

:::{note}
This material is mostly adapted from the following resources:
- [Earth and Environmental Data Science: Numpy and Matplotlib](https://earth-env-data-science.github.io/lectures/basic_scipy/numpy_and_matplotlib.html)
- [Python Programming for Data Science: Chapter 5: Introduction to NumPy](https://www.tomasbeuzen.com/python-programming-for-data-science/chapters/chapter5-numpy.html)
:::

This lecture will introduce NumPy and Matplotlib.
**Numpy** and **Matplotlib** are two of the most fundamental parts of the scientific python ecosystem. Most of everything else is built on top of them.


<img src="https://numpy.org/images/logo.svg" width="100px" />

**Numpy**: _The fundamental package for scientific computing with Python. NumPy is the standard Python library used for working with arrays (i.e., vectors & matrices), linear algebra, and other numerical computations._

- Website: <https://numpy.org/>
- GitHub: <https://github.com/numpy/numpy>

:::{note}
Documentation for this package is available at https://numpy.org/doc/stable/index.html.
:::

<img src="https://matplotlib.org/stable/_images/sphx_glr_logos2_003_2_00x.png" width="300px" />

**Matplotlib**: _Matplotlib is a comprehensive library for creating static and animated visualizations in Python._

- Website: <https://matplotlib.org/>
- GitHub: <https://github.com/matplotlib/matplotlib>

:::{note}
Documentation for this package is available at https://matplotlib.org/stable/index.html.
:::

:::{note}
If you have not yet set up Python on your computer, you can execute this tutorial in your browser via [Google Colab](https://colab.research.google.com/). Click on the rocket in the top right corner and launch "Colab". If that doesn't work download the `.ipynb` file and import it in [Google Colab](https://colab.research.google.com/)

Then install `numpy` and `matplotlib` by executing the following command in a Jupyter cell at the top of the notebook.

```sh
!pip install matplotlib numpy
```
:::

## Importing a Package

This will be our first experience with _importing_ a package.

Usually we import `numpy` with the _alias_ `np`.

In [ ]:
import numpy as np

## NDArrays

NDarrays (short for n-dimensional arrays) are a key data structure in `numpy`. NDarrays are similar to Python lists, but they allow for fast, efficient computations on large arrays and matrices of numerical data. NDarrays can have any number of dimensions, and are used for a wide range of numerical and scientific computing tasks, including linear algebra, statistical analysis, and image processing.

Thus, the main differences between a numpy array and a `list` are the following:
- `numpy` arrays can have N dimensions (while lists only have 1)
- `numpy` arrays hold values of the same datatype (e.g. `int`, `float`), while lists can contain anything.
- `numpy` optimizes numerical operations on arrays. Numpy is _fast!_

<img src="https://predictivehacks.com/wp-content/uploads/2020/08/numpy_arrays.png" width="720px" />

In [ ]:
# create an array from a list
a = np.array([9, 0, 2, 1, 0])

:::{note}
If you're in Jupyter, you can use `<shift> + <tab>` to inspect a function.
:::

In [ ]:
# find out the datatype
a.dtype

In [ ]:
# find out the shape
a.shape

In [ ]:
# another array with a different datatype and shape
b = np.array([[5, 3, 1, 9], [9, 2, 3, 0]], dtype=np.float64)

In [ ]:
# check dtype
b.dtype

In [ ]:
# check shape
b.shape

## Array Creation

There are lots of ways to create arrays.

In [ ]:
np.zeros((4, 4))

In [ ]:
np.ones((2, 2, 3))

In [ ]:
np.full((3, 2), np.pi)

In [ ]:
np.random.rand(5, 2)

In [ ]:
np.arange(10)

In [ ]:
np.arange(2, 4, 0.25)

A frequent need is to generate an array of N numbers, evenly spaced between two values. That is what `linspace` is for.

In [ ]:
np.linspace(2, 4, 20)

Numpy also has some utilities for helping us generate multi-dimensional arrays.
For instance, `meshgrid` creates 2D arrays out of a combination of 1D arrays.

In [ ]:
x = np.linspace(-2 * np.pi, 2 * np.pi, 5)
y = np.linspace(-np.pi, np.pi, 4)
xx, yy = np.meshgrid(x, y)
xx.shape, yy.shape

In [ ]:
yy

In [ ]:
xx

## Indexing

Basic indexing in `numpy` is similar to lists.

In [ ]:
# get some individual elements of xx
xx[3, 4]

In [ ]:
# get some whole rows
xx[0]

In [ ]:
# get some whole columns
xx[:, -1]

In [ ]:
# get some ranges (also called slicing)
xx[0:2, 3:5]

## Visualizing Arrays with Matplotlib

Let's create a slightly bigger array:

In [ ]:
x = np.linspace(-2 * np.pi, 2 * np.pi, 100)
y = np.linspace(-np.pi, np.pi, 50)
xx, yy = np.meshgrid(x, y)
xx.shape, yy.shape

For plotting a 1D array as a line, we use the `plot` command.

To use this function, we first need to import it from the `matplotlib` library.

In [ ]:
from matplotlib import pyplot as plt

The line imports the visualization module `pyplot` from the `matplotlib` library and nicknames it as `plt` for brevity in the code.

In [ ]:
plt.plot(x);

There are many ways to visualize 2D data.
He we use `pcolormesh`.

In [ ]:
plt.pcolormesh(xx);

## Array Operations ##

There is a huge number of operations available on arrays.

All the familiar arithemtic operators are applied on an element-by-element basis.

### Basic Math

In [ ]:
f = np.sin(xx) * np.cos(0.5 * yy)

In [ ]:
plt.pcolormesh(f)

In [ ]:
xx == yy

In [ ]:
np.any(xx == yy)

## Broadcasting


Not all the arrays we want to work with will have the same size!

__Broadcasting__ is a powerful feature in `numpy` that allows you to perform operations on arrays of different shapes and sizes. It automatically expands the smaller array to match the dimensions of the larger array, without actually making copies of the data, so that element-wise operations can be performed. This is done by following a set of rules that determine how the shapes of the arrays align.

Broadcasting allows you to vectorize operations and avoid explicit loops, leading to more concise and efficient code. It's particularly useful when working with large data sets, as it helps optimize memory usage and computational speed.

<img src="http://scipy-lectures.github.io/_images/numpy_broadcasting.png" width="720px" />

Dimensions are automatically aligned _starting with the last dimension_.
If the last two dimensions have the same length, then the two arrays can be broadcast.

In [ ]:
print(f.shape, x.shape)

In [ ]:
g = f * x

In [ ]:
print(g.shape)

In [ ]:
plt.pcolormesh(g)

## Reduction Operations

In data science, we usually start with a lot of data and want to reduce it down in order to make plots of summary tables.

There are many different reduction operations. The table below lists the most common functions:

| Reduction Operation | Description                                                  |
|---------------------|--------------------------------------------------------------|
| `numpy.sum()`       | Computes the sum of array elements over a given axis.         |
| `numpy.mean()`      | Computes the arithmetic mean along a specified axis.          |
| `numpy.min()`       | Computes the minimum value along a specified axis.            |
| `numpy.max()`       | Computes the maximum value along a specified axis.            |
| `numpy.prod()`      | Computes the product of array elements over a given axis.      |
| `numpy.std()`       | Computes the standard deviation along a specified axis.       |
| `numpy.var()`       | Computes the variance along a specified axis.                 |



In [ ]:
# sum
g.sum()

In [ ]:
# mean
g.mean()

In [ ]:
# standard deviation
g.std()

A key property of numpy reductions is the ability to operate on just one axis.

In [ ]:
# apply on just one axis
g_ymean = g.mean(axis=0)
g_xmean = g.mean(axis=1)

In [ ]:
plt.plot(x, g_ymean)

In [ ]:
plt.plot(g_xmean, y)

## Figures and Axes

The *figure* is the highest level of organization of `matplotlib` objects.

In [ ]:
fig = plt.figure()

In [ ]:
fig = plt.figure(figsize=(13, 5))

In [ ]:
fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])

### Subplots

Subplot syntax is a more convenient way to specify the creation of multiple axes.

In [ ]:
fig, ax = plt.subplots()

In [ ]:
ax

In [ ]:
fig, axes = plt.subplots(ncols=2, figsize=(8, 4), subplot_kw={"facecolor": "blue"})

In [ ]:
axes

## Drawing into Axes

All plots are drawn into axes.

In [ ]:
# create some data to plot
import numpy as np

x = np.linspace(-np.pi, np.pi, 100)
y = np.cos(x)
z = np.sin(6 * x)

In [ ]:
fig, ax = plt.subplots()
ax.plot(x, y)

This does the same thing as

In [ ]:
plt.plot(x, y)

This starts to matter when we have multiple axes to manage.

In [ ]:
fig, axes = plt.subplots(figsize=(8, 4), ncols=2)
ax0, ax1 = axes
ax0.plot(x, y)
ax1.plot(x, z)

## Labeling Plots

Labeling plots is very important! We want to know what data is shown and what the units are. `matplotlib` offers some functions to label graphics.

In [ ]:
fig, ax = plt.subplots(figsize=(4, 4))

ax.plot(x, y)
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("x vs. y")

# squeeze everything in
plt.tight_layout()

## Customizing Plots

In [ ]:
fig, ax = plt.subplots()
ax.plot(x, y, x, z)

It's simple to switch axes

In [ ]:
fig, ax = plt.subplots()
ax.plot(y, x, z, x)

### Line Styles

In [ ]:
fig, ax = plt.subplots()
ax.plot(x, y, linestyle="--")
ax.plot(x, z, linestyle=":")

### Colors

As described in the [colors documentation](https://matplotlib.org/stable/api/colors_api.html), there are some special codes for commonly used colors.

In [ ]:
fig, ax = plt.subplots()
ax.plot(x, y, color="black")
ax.plot(x, z, color="red")

### Markers

There are [lots of different markers](https://matplotlib.org/api/markers_api.html) availabile in matplotlib!

In [ ]:
fig, ax = plt.subplots()
ax.plot(x[:20], y[:20], marker="o", markerfacecolor="red", markeredgecolor="black")
ax.plot(x[:20], z[:20], marker="^", markersize=10)

### Axis Limits

In [ ]:
fig, ax = plt.subplots()
ax.plot(x, y, x, z)
ax.set_xlim(-5, 5)
ax.set_ylim(-3, 3)

## Scatter Plots

In [ ]:
fig, ax = plt.subplots()

splot = ax.scatter(y, z, c=x, s=(100 * z**2 + 5), cmap="viridis")
fig.colorbar(splot)

There are many different colormaps available in matplotlib: https://matplotlib.org/stable/tutorials/colors/colormaps.html

## Bar Plots

In [ ]:
labels = ["Reuter West", "Mitte", "Lichterfelde"]
values = [600, 400, 450]

fig, ax = plt.subplots(figsize=(5, 5))
ax.bar(labels, values)

ax.set_ylabel("MW")

plt.tight_layout()

## Exercises

Import `numpy` under the alias `np`.

In [ ]:
import numpy as np

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 $\pi$ values.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [ ]:
np.zeros(5)

In [ ]:
np.ones(10)

In [ ]:
np.full(5, np.pi)

In [ ]:
np.arange(1, 21)

In [ ]:
np.ones((5, 5), dtype=np.int8)

Create a 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: [`np.random.randn()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html))

In [ ]:
np.random.randn(3, 3, 3)

Create an array of 20 linearly spaced numbers between 1 and 10.

In [ ]:
np.linspace(1, 10, 20)

Below I've defined an array of shape 4 x 4. Use indexing to procude the given outputs.

In [ ]:
a = np.arange(1, 26).reshape(5, -1)
a

In [ ]:
a[1:, 3:]

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
a[1]

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
a[2:4]

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [ ]:
a[1:3, 2:4]

```python
array([[ 8,  9],
       [13, 14]])
```

Calculate the sum of all the numbers in `a`.

In [ ]:
a.sum()

Calculate the sum of each row in `a`.

In [ ]:
a.sum(axis=1)

In [ ]:
a.sum(axis=0)

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
a[a > a.mean()]